### ISSUE TITLE
Broken for newer go versions

### ISSUE THREAD

**Issue by nettnikl** [teamortix/golang-wasm#12]
**Describe the bug:**
This package does not compile.
```
..\..\..\go\pkg\mod\github.com\teamortix\golang-wasm\wasm@v0.0.0-20210704024101- 285babe68092\reflect_to.go:34:10: undefined: js.Wrapper
```

**To reproduce:**
Use any version containing this patch:
https://github.com/golang/go/commit/6c0daa733192031eab23d09ed6515c4cd959aa92

**Expected behavior:**
Compiles.

**Additional context:**
Will stay like this, so this lib has to be adjusted to work again, see https://github.com/golang/go/issues/50310

**Comment by hhhapz** [comment]
Feel free to create a PR to fix, seems relatively straightforward to fix

**Comment by nettnikl** [comment]
Wow, that was fast... Many thanks!
