### ISSUE TITLE
Reflection rules out tinygo ?

### ISSUE THREAD

**Issue by gedw99** [teamortix/golang-wasm#7]
Just read the architect md and some of the code .

tinygo does not support reflection and I suspect never will. 
so not sure how this impacts this project but curious on your thoughts

**Comment by hhhapz** [comment]
Most likely will not be possible sadly, as the unexported structs from go objects will never be able to be constructed or retrieved frcmy understand.

**Comment by chanbakjsd** [comment]
From what I can tell, tinygo does support reflection albeit a little limited: https://github.com/tinygo-org/tinygo/tree/e587b1d/src/reflect
I believe that this library should be usable in tinygo somewhat in its current state. Regardless, this library is designed to work with the full standard library currently.
